import type { Metadata } from 'next'

import { Rubik } from 'next/font/google'
import './globals.css'
import HederTop from './components/HederTop'
import HeaderMain from './components/HeaderMain'
import Footer from './components/Footer'

import { getServerSession } from 'next-auth';
// import Sidebar from './components/Sidebar'
import Menu from './components/Menu'



const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
   
  
      <body className={rubik.className}>
         <HederTop />
     <HeaderMain />
{/* <Sidebar /> */}
<Menu />
    {children} 

     <Footer />
   
     </body>
     
   
    </html>
  )
}
